name: Build ruleset and geodata
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> ${GITHUB_ENV}
          echo "singbox_core_old_version=$(curl -sSL https://raw.githubusercontent.com/SagerNet/sing-box/docs/configuration/rule-set/source-format/index.html | awk '/<li>/ {second_last=current; current=$0} END {print second_last}' | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')" >> ${GITHUB_ENV}
          echo "singbox_rules_old_version=$(curl -sSL https://raw.githubusercontent.com/SagerNet/sing-box/docs/configuration/rule-set/source-format/index.html | awk '/<li>/ {second_last=current; current=$0} END {print second_last}' | sed -n 's/^<li>\([0-9]\+\).*/\1/p')" >> ${GITHUB_ENV}
          echo "singbox_core_version=$(curl -sSL https://raw.githubusercontent.com/SagerNet/sing-box/docs/configuration/rule-set/source-format/index.html | awk '/<li>/ {last=$0} END {print last}' | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')" >> ${GITHUB_ENV}
          echo "singbox_rules_version=$(curl -sSL https://raw.githubusercontent.com/SagerNet/sing-box/docs/configuration/rule-set/source-format/index.html | awk '/<li>/ {last=$0} END {print last}' | sed -n 's/^<li>\([0-9]\+\).*/\1/p')" >> ${GITHUB_ENV}
          echo "domains_download_url=https://github.com/DustinWin/domain-list-custom/releases/download/domains" >> ${GITHUB_ENV}
          echo "ips_download_url=https://github.com/DustinWin/geoip/releases/download/ips" >> ${GITHUB_ENV}
        shell: bash

      - name: Clone Repository
        uses: actions/checkout@master

      - name: Checkout DustinWin/domain-list-custom
        uses: actions/checkout@v5
        with:
          repository: DustinWin/domain-list-custom
          path: custom

      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v5
        with:
          repository: v2fly/domain-list-community
          path: community

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./custom/go.mod
          cache-dependency-path: ./custom/go.sum

      - name: Generate `sing-box` geodata
        run: |
          cd ./community/ || exit 1
          go install -trimpath -ldflags="-s -w -buildid=" github.com/metacubex/geo/cmd/geo@master
          for file in $(ls *.dat | sed 's/\.dat$//'); do
            geo convert site -i v2ray -o sing -f "./${file}.db" "./${file}.dat"
          done

      - name: Get geoip relative files
        run: |
          mkdir -p ./sing-box/

          # Download sing-box all geoip files
          singbox_all=($(curl -sSL https://api.github.com/repos/DustinWin/geoip/releases | grep '"browser_download_url"' | grep '/sing-box/' | awk -F '"' '{print $4}'))
          count_singbox_all=${#singbox_all[@]}
          for ((i = 0; i < count_singbox_all; i++)); do
            wget -P ./community/ "${singbox_all[i]}"
          done

      - name: Move `sing-box` geodata files
        run: |
          cd ./community/ || exit 1
          for file in $(ls *.db); do
            install -Dp "./${file}" ../sing-box/
          done
          rm -rf ../custom* ../community*

      - name: Generate `sing-box` rule_set (compatible)
        run: |
          wget "https://github.com/SagerNet/sing-box/releases/download/v${{ env.singbox_core_old_version }}/sing-box-${{ env.singbox_core_old_version }}-linux-amd64.tar.gz" -O - | tar -zxf - -C ./tools/
          mv -f "./tools/sing-box-${{ env.singbox_core_old_version }}-linux-amd64/sing-box" ./tools/sing-box

          mkdir -p ./sing-box-ruleset-compatible/
          cd ./tools/
          sed -i 's/"version": 1/"version": ${{ env.singbox_rules_old_version }}/' ./convert.sh
          chmod +x ./convert.sh && ./convert.sh
          mv -f ./*.json ../sing-box-ruleset-compatible/

      - name: Generate `sing-box` rule_set
        run: |
          wget "https://github.com/SagerNet/sing-box/releases/download/v${{ env.singbox_core_version }}/sing-box-${{ env.singbox_core_version }}-linux-amd64.tar.gz" -O - | tar -zxf - -C ./tools/
          mv -f "./tools/sing-box-${{ env.singbox_core_version }}-linux-amd64/sing-box" ./tools/sing-box

          mkdir -p ./sing-box-ruleset/
          cd ./tools/
          sed -i 's/"version": ${{ env.singbox_rules_old_version }}/"version": ${{ env.singbox_rules_version }}/' ./convert.sh
          chmod +x ./convert.sh && ./convert.sh
          rm -rf ./sing-box* ./rules*
          mv -f ./*.json ../sing-box-ruleset/

      - name: Release and upload `sing-box-ruleset-compatible` assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: sing-box-ruleset-compatible
          tag: sing-box-ruleset-compatible
          overwrite: true
          body: |
            [sing-box](https://github.com/SagerNet/sing-box) rule_set 规则集文件
            适用于 sing-box v${{ env.singbox_core_old_version }}-v${{ env.singbox_core_version }}（不包含）版本的内核（`"version": ${{ env.singbox_rules_old_version }}`）
            规则集文件更新于 ${{ env.update_version }}
          file_glob: true
          file: ./sing-box-ruleset-compatible/*

      - name: Commit and push `sing-box-ruleset-compatible` branch
        run: |
          cd ./sing-box-ruleset-compatible/ || exit 1
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b sing-box-ruleset-compatible
          git add . && git commit -m "sing-box rule_set 规则集文件更新于 ${update_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin sing-box-ruleset-compatible

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 1
